version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/backend
      - static_volume:/usr/src/backend/static
      - media_volume:/usr/src/backend/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1

  frontend:
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    stdin_open: true
    tty: true
    depends_on:
      - backend

  db:
    container_name: postgresql
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  static_volume:
  media_volume:
  node-modules: